---
title: "projet"
format: html
author: "Chloé BRES, Doryan GRAVELEAU & Maëlle HEBRAS"
editor:
  markdown:
    canonical: true
    wrap: 72
---

```{=html}
<style>
body {
text-align: justify}
</style>
```
```{r init, include=FALSE}
#Configuration de la session et chargement des packages R
rm(list=ls()) # Nettoie l'espace de travail
library(knitr)
opts_chunk$set(echo = FALSE, comment = "", cache = TRUE, fig.align = "center")
library(rmarkdown) 
library(markdown)
library(ggplot2) # Package pour les graphiques
library(tinytex) # Pour la sortie pdf
library(corrplot)# Calcul d'une matrice de correlation
library(plot3D)# 3D plot
```

# INTRODUCTION GENERALE

## PRESENTATION DES DONNEES ET DES OBJECTIFS DE L'ANALYSE

Pour cet exercice, nous utiliserons les données d'une étude réalisée par
Philippe Vernon - Université de Rennes 1 (1994) et qui concerne la
mouche *Anatalanta aptera*, une mouche aptère vivant dans les colonies
d'oiseaux marins des îles subantarctiques. Au début des années 90, P.
Vernon a collecté de nombreux individus sur l'archipel de Crozet. Il a
ainsi échantillonné sur le littoral et à l'intérieur des terres (i.e.
paysage de relief). L'objectif principal de cette étude est de
déterminer les variables expliquant le poids sec d'*Anatalanta aptera*.
Le poids sec, désignant le poids de l'animal après qu'il ait été séché
dans une étuve, représente la matière organique et inorganique totale
contenues chez un individu. Cette métrique serait plus précise que la
mesure du poids : le poids sec est une mesure fiable de la croissance et
est un bon indicateur du contenu énergétique d'un individu.

Après l'échantillonnage, P. Vernon a identifié et mesuré en laboratoire
les traits d'histoire de vie suivants :\
- **Sex** = le sexe d'un individu donné, variable qualitative\
- **Habitat** = l'habitat d'un individu donné ('Coast' or 'Inland'),
variable qualitative\
- **Length** = la longueur d'un individu donné, variable quantitative\
- **Width** = la largeur d'un individu donné, variable quantitative\
- **WaterContent** = le poids en eau d'un individu donné, variable
quantitative\
- **FatContent** = le poids lipidiques d'un individu donné, variable
quantitative\
- **DryWeight** = le poids sec d'un individu donné, variable
quantitative

La variable réponse est le poids sec et les autres variables sont
supposées être des variables explicatives. La question sous-jacente à
cette étude est : quelles variables quantitatives (i.e. covariables) et
qualitatives (i.e. facteurs) déterminent le poids sec chez *Anatalanta
aptera* ?

Les données figurent dans le fichier FlyWeight.txt.

## METHODE UTILISEE

Comme l'ANOVA et la régression linéaire, l'ANCOVA (i.e. analysis de
variance-covariance) est une méthode statistique très utilisée dans
diverses disciplines. Elle permet de modéliser la relation entre une
variable dépendante quantitative $Y$ selon plusieurs variables
explicatives **quantitatives ET qualitatives** $X_{1}$,$X_{2}$...$X_{p}$
(i.e. les variables indépendantes). Par exemple, nous pouvons utiliser
une ANCOVA pour tester si la taille (variable quantitative), le sexe
(variable qualitative), le statut reproductif (variable qualitative),
l'habitat (variable qualitative), l'âge (variable quantitative) d'un
cachalot expliquent en partie son poids (variable réponse). Comme
l'ANCOVA inclut des variables explicatives quantitatives et
qualitatives, cette méthode statistique se situe entre la régression
linéaire et l'ANOVA.

# CONCLUSION

Grâce à l'ANCOVA, nous avons réussi à proposer un modèle permettant
d'expliquer selon quelles variables et intéractions le poids sec d'un
individu varie. Nous avons conserver uniquement les variables expliquant
le mieux le poids sec et nous avons enlevé les variables apportant en
autre de la redondance d'information.

Le modèle a été validé, d'une par par **l'homogénéité des résidus**, et
d'autre part par également la **normalité des résidus**.

Par la suite, il serait intéréssant de comprendre, d'un point de vue
biologique, physiologique ou génétique peut-être, comment s'effectue la
variation du poids chez les individus.
