---
title: "analyse_données_bois"
author: "Nicolas Chevillon, Anaëlle Baron, Eli Desnyder"
date: "2026-09-16 10:20:40 CEST "
bibliography: references.bib
execute: 
  freeze: auto
editor:
  markdown:
    canonical: true
    wrap: 72
format: html
css: theme.css
toc: true
toc_float: true
---

PREPARING THE WORKING SPACE

```{r}
#Importing needed packages
library(data.table)
library(ggplot2)
library(maps)
library(dplyr)

#Importing the file with individual wood density measurements(xdm_individual_density_data.csv file)
XDM_individual_density_data = data.table(read.table("xdm_individual_density_data.csv",
                                                    sep = ",", dec= ".", header = TRUE))

#Creating a datatable with only 1 species: Quercus robur
dta_Qrobur = filter(XDM_individual_density_data, XDM_individual_density_data$Species == "Quercus robur")
#Transforming Core_Type, Botanical_Class, Species into factors
dta_Qrobur$Botanical_Class=as.factor(dta_Qrobur$Botanical_Class)
dta_Qrobur$Species=as.factor(dta_Qrobur$Species)
dta_Qrobur$Core_Type=as.factor(dta_Qrobur$Core_Type)

#Removing the NA for the Age
dta_Qrobur = dta_Qrobur%>% filter(!is.na(Age))

colSums(is.na(dta_Qrobur))

```

EPXLORATION OF THE DATASET

```{r}
par(mfrow=c(3,1))
#Scatter plot of the relationship between tree diameter at breast height (DBH) and wood density in Quercus robur
ggplot(data = dta_Qrobur, aes(x = DBH, y = WDbw)) +
  geom_point() +
  geom_smooth(method = "gam", formula = y ~ s(x, k = 10)) + #Adding a smooth line based on generalized additive models
  xlab(label = "Diameter at breast height (m)") +
  ylab(label = bquote('Wood density '(kg.m^-3)))

#Scatter plot of the relationship between the mean basic wood density and the weighted mean basic wood density in Quercus robur
ggplot(data = dta_Qrobur, aes(x = WDb, y = WDbw)) +
  geom_point() +
  geom_smooth(method = "lm") + #Adding the linear regression line
  geom_abline(slope = 1, intercept = 0, linetype = "dotted") + #Adding the Y=X line
  xlab(label = bquote('Mean basic wood density '(kg.m^-3))) +
  ylab(label = bquote('Weighted mean basic wood density '(kg.m^-3)))

#Map of the average wood density (weighted mean basic wood density) on each NFI forest plot (using approximate coordinates, as the exact coordinates of the NFI plots are not available for statistical confidentiality reasons)
france = map_data('france') #Extracting the map of France using the map_data function of maps package
dta_Qrobur_map = dta_Qrobur[, .(mean = mean(WDbw)), by = c("Plot_ID", "X", "Y")] #Creating a new table with the average wood density (weighted mean basic wood density) for each NFI forest plot
ggplot(data = france, aes(x = long,y = lat, group = group)) + #Drawing the map
  geom_polygon(fill = "white", colour = "black") +
  geom_point(data = dta_Qrobur_map, size = 0.5, aes(x = X, y = Y, group = 1, colour = mean)) +
  scale_color_gradient2(low = "blue", mid = "tan", high = "red", midpoint = 600)

```

ANALYSING INTERACTIONS BETWEEN Y and Xs

ANALYSING INTERACTIONS BETWEEN Xs VARIABLES

VERIFYING ANY COLINEARITY

TRYING MODELISATION Objectif : on cherche les variables qui expliquent
la variation de densité du bois (*WD0w*) parmis les variables suivantes
: - *X*, *Y*, et *Z* : les données de localisation de l'arbre observé -
*Core-Type* - *Core_Length* - *Age* - *DBH* - *H* - *TM* - *P*

```{r}
# Model formulation
mod1<-lm(WD0w ~ X+Y+Z+P+Core_Length+Age+DBH+H+TM+P
         ,data=dta_Qrobur)
# Then we check for significance
drop1(mod1,test="F")
summary(mod1)

```
